### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by yechunsen** [skyplaying/maxi#1]
- [x] 1. 点击maxi logo或launchpad回首页
- [x] 2. 点击marketplace、stats、airdrop回
- [x] 3. 搜索icon现在没有出现
- [x] 4. 切换黑暗和白天模式的按钮先隐藏，只要暗黑模式
- [x] 5. 卡片改小(先整体缩小至80%)
- [x] 6. container 改为1280
- [x] 7. 详情页
- [x] 8. 连钱包
- [ ] 9. 后端联调
- [ ] 10. 合约联调
- [x] 11. footer只放hello@maxi.to和推特，其他都不放
- [x] 12. 全站字体设置montserrat，包括footer tag筛选器
- [ ] 13. p1-加入tag筛选、分页
- [ ] 14. p1-手机适配
- [x] 15. p2-favicon改为我们的icon
- [x] 16.详情页tip
- [ ] 17.详情页白皮书、merbership policy 跳转
- [ ] 18.QA区域文案

**Comment by yechunsen** [comment]
Minting now : 一般同时mint中的项目不会超过十个，因此无需分页，如果没有正在mint的项目则不显示
Upcoming：项目较多，约有100个，因此需要有分页（或load more）、筛选和排序。默认PC每页12个，mobile不分页，但一次展示12个，到底后点击load more加载下一页。 筛选器可以按照标签筛选（预设约20个标签）。排序按照默认（服务器设定的顺序）、mint时间、Twitter粉丝数、discord粉丝数。
Ended：前期项目少，但主网上线后项目会越来越多。默认PC每页4个，mobile不分页，但一次展示4个。如果没有项目展示EMPTY。筛选器可以按照标签筛选（预设约20个标签）。排序可按照默认（服务器设定的顺序）、mint时间、mint单价、mint总金额、Twitter粉丝数、discord粉丝数。
